
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 02 11:04:43 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 12;
  public static final int IDF = 31;
  public static final int EGAL = 7;
  public static final int CSTENTIERE = 32;
  public static final int OU = 29;
  public static final int PLUS = 13;
  public static final int LIRE = 8;
  public static final int INFERIEUR = 20;
  public static final int ECRIRE = 6;
  public static final int FOIS = 15;
  public static final int PARENOUV = 9;
  public static final int FONCTION = 11;
  public static final int TANTQUE = 25;
  public static final int ALORS = 22;
  public static final int SUPERIEUR = 19;
  public static final int DIFFERENT = 17;
  public static final int REPETER = 26;
  public static final int NON = 30;
  public static final int FINTANTQUE = 27;
  public static final int MOINS = 14;
  public static final int POINTVIRGULE = 5;
  public static final int SINON = 23;
  public static final int TYPE = 33;
  public static final int EOF = 0;
  public static final int EGALEGAL = 18;
  public static final int ET = 28;
  public static final int SI = 21;
  public static final int DIVISE = 16;
  public static final int error = 1;
  public static final int DEBUT = 3;
  public static final int FINSI = 24;
  public static final int PARENFERM = 10;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

